#!/bin/bash -e
## exit on non-zero status
set -e

## define repository
REPO=products/tcltk.git
HOST=gitlab.auk.cvclab.lan

## info
VERSION=1.1
MANUFACT="(c) 2019 ATOS"
AUTHORS="Thomas Perschak"

## helper functions
##
function printHelp {
    echo "GIT working folder setup script, Version $VERSION"
    echo "$MANUFACT, $AUTHORS"
    echo "Syntax:"
    echo " setgit [-author <committers name> -email <e-mail> -type public|private]"
    echo "Options:"
    echo " -author <committers name>: Specify who is committing. Current value '$GAUTHOR'."
    echo " -email <e-mail>: A valid e-mail address. Current value '$GEMAIL'."
    echo " -type public|private: A public type uses http, a private type uses ssh to access the repository. Current value '$TYPE'."
    echo " -help: Print this help text."
    echo "Origin:"
    echo " $GORIGIN"
}

## defaults
GORIGIN=$(git config remote.origin.url) || true
if [ "${GORIGIN:0:4}" == "http" ]; then TYPE="public"; else TYPE="private"; fi
GAUTHOR=$(git config user.name) || true
GEMAIL=$(git config user.email) || true

## read command line parameters
INDEX=1
while [ $INDEX -le $# ]; do
    case ${!INDEX} in
        "-author")
            let INDEX+=1
            GAUTHOR=${!INDEX}
            ;;
        "-email")
            let INDEX+=1
            GEMAIL=${!INDEX}
            ;;
        "-type")
            let INDEX+=1
            TYPE=${!INDEX}
            ;;
        "-help")
            printHelp
            exit 1
            ;;
        *)
            echo "Unknown parameter '${!INDEX}', type -help for more information." >&2; exit 1
            ;;
    esac
    let INDEX+=1
done

## check
if [ $TYPE != "public" ] && [ $TYPE != "private" ]; then echo "Type must be public|private" >&2; exit 1; fi
if [ -z "$GAUTHOR" ]; then echo "Missing author" >&2; exit 1; fi
if [ -z "$GEMAIL" ]; then echo "Missing e-mail" >&2; exit 1; fi
PATTERN="^[A-Za-z0-9]+[A-Za-z0-9._]*+@[A-Za-z0-9-]+\.[A-Za-z]{2,4}$"
if [[ ! $GEMAIL =~ $PATTERN ]]; then echo "Malformed e-mail address" >&2; exit 1; fi

## construct origin
if [ $TYPE == "public" ]; then
    ORIGIN=http://$2@$HOST/gitlab/$REPO
else
    ORIGIN=gitlab@$HOST:$REPO
fi

## configure
git remote set-url origin $ORIGIN
git config user.name $GAUTHOR
git config user.email $GEMAIL
if [ "$(lsb_release -sc)" == "trusty" ]; then
    git config push.default simple
fi

