#!/bin/bash -e

## get install info
BUILDOS="%build_os%"
BUILDKERNELNAME=%build_kernelname%
BUILDKERNELRELEASE="%build_kernelrelease%"
BUILDKERNELVERSION="%build_kernelversion%"
BUILDNODENAME=%build_nodename%
BUILDMACHINE=%build_machine%
GITHASH=%git_hash%
GITBRANCH=%git_branch%
DEBNAME=%deb_name%
DEBVERSION=%deb_version%
DEBFILE=%deb_file%
INSTDIR=%inst_dir%
BINDIR=%bindir%

case "$1" in
    install|upgrade)
	if [ "$1" == "upgrade" ]; then
	    OLDVERSION=$2
	    echo "Running $DEBNAME preinst '$1', old version $OLDVERSION ..."
	else
	    echo "Running $DEBNAME preinst '$1' ..."
	fi
esac

## fini
exit 0
